config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :likes
  resources :questions do 
    resources :comments
  end
  root 'welcome#index'

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks', sessions: 'customers/sessions' },
             path_names: { sign_in: 'login', sign_out: 'logout' }

  get '/check_mobile_login', to: 'customers#check_mobile_login'
  get '/customer/orders', to: 'customers#orders'
  get '/comments/test', to: 'comments#test'
  get '/gett', to: 'questions#gett'
  


  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :customer
    belongs_to :comment
end

app/controllers/likes_controller.rb
class LikesController < InheritedResources::Base
  
  def create
    #new_question = Question.create()
    
    order_items_json = params['_json']
    order_items_json.each do |item|
      puts item
      @like= Like.create(
          customer_id: current_customer.id,
          comment_id: item['comment_id'],
          counter: item['counter']
      )
      
    end
    render json: ["id": @like.id]
  end

  def destroy
    puts "Deeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
        @like= Like.find(params[:id])
        puts "daaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        @like.destroy
  end


  def update
    puts "update the like"
    Like.update(params[:id], :counter => Integer(params[:counter]))
  end

  private

    def like_params
      params.require(:like).permit(:customer_id, :comment_id)
    end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_with(model: like, local: true) do |form| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :comment_id %>
    <%= form.number_field :comment_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.customer_id %></td>
        <td><%= like.comment_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @like.customer_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @like.comment_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>